### ISSUE TITLE
Titlebar of 'Insert note' is Chinese or Japanese

### ISSUE THREAD

**Issue by MrMacvos** [calandradas/Kityminder-Mindmap-Joplin-Plugin#1]
Hi,

I just installed your plugin and when I want to add a Note to a branch, I see this, although my macOS is in English and Joplin is in English too:

<img width="383" alt="Screenshot 2024-01-14 at 12 59 17" src="https://github.com/calandradas/Kityminder-Mindmap-Joplin-Plugin/assets/1470464/b20a8fda-1ca3-465c-9c51-f5d00353c685">

Also the background colors menu:

<img width="252" alt="Screenshot 2024-01-14 at 14 50 09" src="https://github.com/calandradas/Kityminder-Mindmap-Joplin-Plugin/assets/1470464/4adbae02-36bf-49f4-a668-e4b206ee5bb5">

Joplin v2.13.14

**Comment by calandradas** [comment]
v0.8.3 already resolved this bug, you can try it,
 And English is default language, you can also change it at menu tools->options->plugins->kitymind mindmap. Thanks and tell me if you find any issues.

**Comment by calandradas** [comment]
closed
