### ISSUE TITLE
I didn't see any mind maps saved.

### ISSUE THREAD

**Issue by kid-pc-chen** [calandradas/Kityminder-Mindmap-Joplin-Plugin#2]
您的插件補充了 kity minder plugin 無法匯入 xmind 的不足
非常感謝您的貢獻
但是我在 Joplin 2.14.20 Windows 版安裝了您的插件後，測試了一下，當我按下 save後，卻沒有看到任何 mind map 被儲存下來
是我遺漏了什麼嗎？
謝謝

Your plugin complements the shortcomings of the kity minder plugin that cannot import xmind.
Thank you very much for your contribution.
However, after I installed your plugin on Joplin 2.14.20 Windows version. However, I tried to draw something and pressed save, I didn't see any mind maps saved.
Did I miss anything?
Thank you.

**Comment by calandradas** [comment]
能否提供一下你的操作事例文件和操作步骤，以便于我能够调试。多谢！

**Comment by pcchen-kid** [comment]
不太確定是否是 Joplin 本身的 bug，我今天重啟 Joplin，kminder plugin 就一切正常了。(昨天無論怎麼重啟 Joplin 都無法 save)
很抱歉佔用您寶貴的時間。您可以先 close issue 了，如果有新的狀況在跟您回報。謝謝。

Not sure if it is a Joplin bug itself.
I restarted Joplin today, and the kminder plugin works fine.
(Yesterday, no matter how I restarted Joplin, I couldn't save.)

I'm sorry to take up your time.
You can close the issue for now.

I will report back to you if there are any new situations. Thank you
